# A sample Gemfile
source "https://rubygems.org"

# serverspec gems
gem 'rake'
gem 'serverspec'
gem 'rspec'

# Puppet gems
gem 'puppet'
gem 'librarian-puppet'
gem 'puppet-lint'

# Capistrano gems
gem 'capistrano'
